### ISSUE TITLE
wish: document relationship between fallback.ready() and jQuery's ready function

### ISSUE THREAD

**Issue by markstos** [dolox/fallback#2]
fallback.js provides's it's own ready() method, as does jQuery. 

Some documentation would be helpful to clarify how they expected to be used together. Do you call Jquery's ready() method from within the fallback ready() method? Vice-versa? Or is one used instead of the other?

Some simple docs and an example would be helpful.

**Comment by sgarbesi** [comment]
jQuery's .ready() executes after the DOM is ready which will not work here as you are loading the JS libraries after the DOM is ready.

Instead of using jQuery's .ready() you use fallback's .ready() function.

There should be an example in the example.html file in the repository.

Yes, I plan on updating the documentation so it gives a more thorough explanation.

**Comment by markstos** [comment]
Thanks for super-fast reply. I found the example.html now and see it shows fallback.ready() being used in place of the  jQuery ready() method:

https://github.com/sgarbesi/fallback.js/blob/master/example.html

I just gave your project a little shout-out on Twitter as well:

https://twitter.com/MarkStosberg/status/345227082655232000

**Comment by sgarbesi** [comment]
No problem, check back I'll make a note to try and update the documentation for this weekend.

Thanks for the shout!
