### ISSUE TITLE
Requiring bootstrap from cdn using fallback.js v2 causes glyphicons to be loaded from localhost

### ISSUE THREAD

**Issue by mad-gooze** [dolox/fallback#52]
I am trying to include Bootstrap using Fallback.js from CDN with local server fallback like this:

``` javascript
fallback.config({
    libs: {
        "css$bootstrap": {
            exports: ".col-xs-12",
            urls: [
                "//maxcdn.bootstrapcdn.com/bootswatch/3.3.6/paper/bootstrap.min",
                "lib/bootstrap.min"
            ]
        }
    }
});
fallback.require("css$bootstrap")
```

This causes glypthicons font files to be loaded from local server (it seems like this happens because Fallback.js loads files using AJAX and bootstrap CSS contains a relative path for glypthicons font files - is that correct?).

How can this can be fixed?

**Comment by Brad-Christie** [comment]
Relative path would still be relative to _that_ file (in this case the remote location).

I think this related to the same issue (or behavior) I'm seeing as well, though. Though I'm attempting to use the CDN, it's consistently falling back to my local stylesheets. I'm thinking this is because `document.styleSheets` falls victim to CORS protections. That is to say, when you load jQuery from a CDN, it's irrefutable that `window.jQuery` becomes defined. However, testing for `.col-xs-12` (for example) that's added via a stylesheet coming from another domain causes a [known false result](https://github.com/dolox/fallback/blob/v2/src/loaderStylesheet.js#L104-L118) (and fails due to browser security and not necessarily because it wasn't loaded). So what happens then? The fallback is loaded atop the remote.

Maybe there's a [work-around](http://stackoverflow.com/questions/3211536/accessing-cross-domain-style-sheet-with-cssrules) to this?

**Comment by sgarbesi** [comment]
@MAD-GooZe @Brad-Christie 

**HTML:**

``` html
<base href="http://bootstrap-cdn-files/" />
```

Of course this would require you to use absolute paths for all of your other local files. There's not much that can be done here, this is simply how the browsers work.

What would I do?

Find the CSS attribute that bootstrap uses to require the font and forcefully override it to use the CDN so that the path the browser tries to load for the font is from the CDN and not local.

Example:

**bootstrap.css:** (untouched, original copy)

``` css
.glyph {
    font: src('../../some-local-path/font.woff');
}
```

**my-override-css:** (custom CSS hosted locally)

``` css
.glyph {
    font: src('http://please-use-the-cdn-thanks/font.woff') !important;
}
```
